[package]
name = "ppi_predict"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
goombay-rs = { git = "https://github.com/lignum-vitae/goombay-rs" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
